## DOCS:
## https://pipelinesascode.com/docs/guide/repositorycrd/#concurrency
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: terraform-provider-avgcp
  namespace: tfm
spec:
  url: "https://github.com/ArthurVardevanyan/terraform-provider-avgcp"
  concurrency_limit: 3