---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tfp-avgcp-test
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "1"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/ArthurVardevanyan/HomeLab/main/tekton/tasks/git-clone/0.9.1/git-clone.yaml"
    pipelinesascode.tekton.dev/target-namespace: "tfm"
spec:
  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: git-commit
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: git-url
        description: Repository URL to clone from.
        type: string
      - name: git-commit
        type: string

    workspaces:
      - name: data
      - name: git_auth_secret

    tasks:
      - name: git-clone
        taskRef:
          name: git-clone
          kind: Task
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.git-commit)
        workspaces:
          - name: output
            workspace: data
          - name: basic-auth
            workspace: git_auth_secret

      - name: test-build
        runAfter:
          - git-clone
        workspaces:
          - name: output
            workspace: data
        params:
          - name: revision
            value: $(params.git-commit)
        taskSpec:
          workspaces:
            - name: output
              optional: false
          stepTemplate:
            name: stepTemplate
            resources:
              requests:
                memory: 500Mi
                cpu: 500m
                ephemeral-storage: 100Mi
              limits:
                cpu: "4"
                memory: 5Gi
                ephemeral-storage: 100Mi
            securityContext:
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: gcp-credentials-request
              configMap:
                name: gcp-credentials-request
                defaultMode: 420
            - name: serviceaccount-token
              projected:
                sources:
                  - serviceAccountToken:
                      audience: openshift
                      expirationSeconds: 3600
                      path: token
                defaultMode: 420
          steps:
            - name: test
              image: registry.arthurvardevanyan.com/homelab/toolbox:latest
              env:
                - name: WORKSPACE_DATA_PATH
                  value: $(workspaces.output.path)
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/run/secrets/google/credentials_config.json
                - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
                  value: /var/run/secrets/google/credentials_config.json
              volumeMounts:
                - name: cache
                  mountPath: /tmp
                - name: gcp-credentials-request
                  readOnly: true
                  mountPath: /var/run/secrets/google
                - name: serviceaccount-token
                  readOnly: true
                  mountPath: /var/run/secrets/openshift/serviceaccount
              script: |
                set -o errexit
                set -o nounset
                set -o pipefail

                cd ${WORKSPACE_DATA_PATH}
                git config --global --add safe.directory "${WORKSPACE_DATA_PATH}"

                export GCP_SERVICE_ACCOUNT=$(jq --raw-output .service_account_impersonation_url "${GOOGLE_APPLICATION_CREDENTIALS}" | rev | cut -d/ -f1 | rev | cut -d: -f1)

                make

  serviceAccountName: pipeline
  workspaces:
    - name: data
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "100Mi"
          storageClassName: longhorn
    - name: git_auth_secret
      secret:
        secretName: "{{ git_auth_secret }}"
